### ISSUE TITLE
Undefined method 'plist_startup' on running service

### ISSUE THREAD

**Issue by adinklotz** [erikw/restic-automatic-backup-scheduler#133]
I'm getting an error trying to set up the service:
```
❯ brew services start restic-automatic-backup-scheduler
Error: undefined method `plist_startup' for #<Formula restic-automatic-backup-scheduler (stable) /opt/homebrew/Library/Taps/erikw/homebrew-tap/Formula/restic-automatic-backup-scheduler.rb>
Did you mean?  plist_name
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/formula_wrapper.rb:71:in `service_startup?'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:280:in `service_load'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:122:in `block in start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:97:in `start'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:130:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

It [sounds like](https://stackoverflow.com/questions/77659527/mongodb-via-brew-services-undefined-method-plist-startup) this may be related to a recent breaking change to Homebrew service definitions - it looks like hopefully a quick fix but unfortunately I don't have the understanding of homebrew internals or time to learn them right now

Running Homebrew 4.2.2-4-g080e61f, macOS 14.2.1

**Comment by jjdevega** [comment]
I am getting the same error, macOS 13.6.1 and homebrew 4.2.3 (freshly reinstalled).

**Comment by olalonde** [comment]
Same error. It looks like brew is not creating the `~/Library/LaunchAgents/homebrew.mxcl.restic-automatic-backup-scheduler.plist` file.

**Comment by johnsturgeon** [comment]
Fix appears to be this
```
diff --git a/lib/service/formula_wrapper.rb b/lib/service/formula_wrapper.rb
index 095b58a..c5b6d0c 100644
--- a/lib/service/formula_wrapper.rb
+++ b/lib/service/formula_wrapper.rb
@@ -68,7 +68,7 @@ module Service
         return @service_startup
       end

-      @service_startup ||= formula.plist_startup.present?
+      @service_startup ||= formula.plist_name.present?
     end

     # Path to destination service directory. If run as root, it's `boot_path`, else `user_path`.
```

**Comment by vvsor** [comment]
Mac OS Sequoia 15.2 + Homebrew 4.4.15:

```shell
❯ brew services start restic-automatic-backup-scheduler
==> Successfully started `restic-automatic-backup-scheduler` (label: homebrew.mxcl.restic-automatic-backup-scheduler)
```

**Comment by erikw** [comment]
That looks like success to me, unless I missed something in that output. Thanks you for testing!
